const REGIONS = [
  {
    id: 'japan',
    name: 'Japan',
    subtitle: 'Prefectures',
    emoji: '🇯🇵',
    svgFile: 'maps/japan.svg',
    shapeSelector: '.prefecture',
    total: 47,
  },
  {
    id: 'usa',
    name: 'USA',
    subtitle: 'States',
    emoji: '🇺🇸',
    svgFile: 'maps/usa.svg',
    shapeSelector: '.geo-shape',
    total: 51,
  },
  {
    id: 'europe',
    name: 'Europe',
    subtitle: 'Countries',
    emoji: '🇪🇺',
    svgFile: 'maps/europe.svg',
    shapeSelector: '.geo-shape',
    total: 45,
  },
  {
    id: 'asia',
    name: 'Asia',
    subtitle: 'Countries',
    emoji: '🌏',
    svgFile: 'maps/asia.svg',
    shapeSelector: '.geo-shape',
    total: 46,
  },
  {
    id: 'africa',
    name: 'Africa',
    subtitle: 'Countries',
    emoji: '🌍',
    svgFile: 'maps/africa.svg',
    shapeSelector: '.geo-shape',
    total: 55,
  },
  {
    id: 'latam',
    name: 'South & Latin America',
    subtitle: 'Countries',
    emoji: '🌎',
    svgFile: 'maps/latam.svg',
    shapeSelector: '.geo-shape',
    total: 33,
  },
  {
    id: 'oceania',
    name: 'Oceania',
    subtitle: 'Countries',
    emoji: '🏝️',
    svgFile: 'maps/oceania.svg',
    shapeSelector: '.geo-shape',
    total: 14,
  },
  {
    id: 'australia',
    name: 'Australia',
    subtitle: 'States & Territories',
    emoji: '🇦🇺',
    svgFile: 'maps/australia.svg',
    shapeSelector: '.geo-shape',
    total: 8,
  },
];
